SESSION_INACTIVE_TIMEOUT = 1800

MONGODB_HOST = 'mongodb'
MONGODB_PORT = 27017
MONGODB_DB_NAME = 'media_db'
MONGODB_USER_COLLECTION_NAME = 'users'
MONGODB_SESSION_COLLECTION_NAME = 'sessions'

FILES_DIRECTORY = '/service-files'